project_id = "qtsxwyekivsnjdlpwdjl"

[functions.generate-meal-plan]
verify_jwt = true

[functions.process-weekly-feedback]
verify_jwt = true

[functions.suggest-meal-alternatives]
verify_jwt = true

[functions.predict-patterns]
verify_jwt = true