project_id = "qtsxwyekivsnjdlpwdjl"

[functions.get-food-nutrition]
verify_jwt = true

[functions.create-diet-plan]
verify_jwt = true

[functions.generate-meal-plan]
verify_jwt = true

[functions.generate-meal-suggestions]
verify_jwt = true

[functions.process-weekly-feedback]
verify_jwt = true

[functions.suggest-meal-alternatives]
verify_jwt = true

[functions.predict-patterns]
verify_jwt = true

[functions.analyze-client-groups]
verify_jwt = true

[functions.generate-client-report]
verify_jwt = true

[functions.batch-update-plans]
verify_jwt = true